mi/urls.py
from django.urls import path
from mi.views import *
app_name='ss'
urlpatterns=[
    path('rohit/',rohit,name='rohit')
]

project21/urls.py
from django.contrib import admin
from django.urls import path,include
import mi
from rcb.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mi/',include('mi.urls')),
    path('virat/',virat,name='virat'),
]

mi/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

mi/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,'rohit.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'virat' %}">
    <h1>welcome to mi</h1>
    </a>
     
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'ss:rohit'%}">
        <center>
            <h1>welcome to rcb</h1>
        </center>
    </a>
</body>
</html>